### ISSUE TITLE
 g2-react 1.0.1 和 g2 2.0.0 版本兼容问题

### ISSUE THREAD

**Issue by stand1921** [antvis/g2-react#5]
我 npm安装 g2-react 1.0.1 和 "g2 2.0.0, 报错说g2-react 需要 g2 1.2.6，但是npm安装g2 1.2.6后报错 g2@1.2.6  invalid
 实际使用g2-react 1.0.1 和 g2 2.0.0时，webpack 编译时报以下错：

ERROR in ./~/g2-react/lib/index.js
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/home/j/stockfront/node_modules/g2-react/package.json" at 0, attempted to resolve relative to "/home/j/stockfront/node_modules/g2-react"
    at /home/j/stockfront/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (/home/j/stockfront/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/home/j/stockfront/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/home/j/stockfront/node_modules/babel-core/lib/transformation/file/options/option-manager.js:338:12)
    at File.initOptions (/home/j/stockfront/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/j/stockfront/node_modules/babel-core/lib/transformation/file/index.js:137:24)
    at Pipeline.transform (/home/j/stockfront/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/j/stockfront/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/home/j/stockfront/node_modules/babel-loader/index.js:131:12)
 @ ./src/scripts/index2.jsx 21:15-34

**Comment by jaredleechn** [comment]
```
{
  "dependencies": {
    "g2": "^1.2.6",
    "g2-react": "~^1.0.1"
  }
}
```

保留 package.json 中的上述，删除 node_modules，重新安装


`g2-react@1.x` 是对 `g2@1.x` 的封装，2.0 的封装暂时还没有，@simaQ 来个 commit？

**Comment by simaQ** [comment]
好的呢！搞一个！

**Comment by jaredleechn** [comment]
peerDeps from `~` to `^`
