### ISSUE TITLE
使用的时候报 document is not defined 的错误

### ISSUE THREAD

**Issue by chenjianjun571** [antvis/g2-react#61]
/Users/chenjianjun/Documents/gitproc/HIMS/front/web/node_modules/g2/index.js:7
t.__cfg.canvas=e.__cfg.canvas,t.__cfg.totalMatrix=null;var n=t.__attrs.clip;n&&(n.setSilent("parent",e),n.setSilent("context",e.get("context")));var i=t.__cfg.children;i&&a.each(i,function(e){t.__setEvn(e)})},getBBox:function(){var t=this,e=1/0,n=-(1/0),i=1/0,r=-(1/0),o=t.get("children");a.each(o,function(t){if(t.get("visible")){var a=t.getBBox();if(!a)return!0;var o=new s(a.minX,a.minY,1),u=new s(a.minX,a.maxY,1),c=new s(a.maxX,a.minY,1),l=new s(a.maxX,a.maxY,1);t.apply(o),t.apply(u),t.apply(c),t.apply(l);var h=Math.min(o.x,u.x,c.x,l.x),f=Math.max(o.x,u.x,c.x,l.x),g=Math.min(o.y,u.y,c.y,l.y),p=Math.max(o.y,u.y,c.y,l.y);h<e&&(e=h),f>n&&(n=f),g<i&&(i=g),p>r&&(r=p)}});var u={minX:e,minY:i,maxX:n,maxY:r};return u.x=u.minX,u.y=u.minY,u.width=u.maxX-u.minX,u.height=u.maxY-u.minY,u},drawInner:function(t){for(var e=this.get("children"),n=0;n<e.length;n++){var i=e[n];i.draw(t)}return this},getCount:function(){return this.get("children").

ReferenceError: document is not defined
    at Object.<anonymous> (/Users/chenjianjun/Documents/gitproc/HIMS/front/web/node_modules/g2/index.js:7:13165)
    at e (/Users/chenjianjun/Documents/gitproc/HIMS/front/web/node_modules/g2/index.js:1:319)
    at Object.<anonymous> (/Users/chenjianjun/Documents/gitproc/HIMS/front/web/node_modules/g2/index.js:3:29927)

**Comment by chenjianjun571** [comment]
import createG2 from 'g2-react';
import { Stat, Frame } from 'g2';
import React from "react";

const Line = createG2(chart => {
  chart.setMode('select'); // 开启框选模式
  chart.select('rangeX'); // 设置 X 轴范围的框选
  chart.cols({ 
    '..count': {
      alias: 'top2000 唱片总量'
    },
    release: {
      tickInterval: 5,
      alias: '唱片发行年份'
    }
  });
  chart.interval().position(Stat.summary.count('release')).color('#e50000');
  chart.render();
  // 监听双击事件，这里用于复原图表
  chart.on('plotdblclick', function(ev) {
    chart.get('options').filters = {}; // 清空 filters
    chart.repaint();
  });
});

class Home extends React.Component {
  state = {
    data: Frame.sort(new Frame(data), 'release') ,
    width: 500,
    forceFit: true,
    height: 450,
    plotCfg: {
      margin: [20, 60, 80, 120]
    },
  }

  render() {
    return (
      <div>
        <Line
          data={this.state.data}
          width={this.state.width}
          height={this.state.height}
          forceFit={this.state.forceFit}
          plotCfg={this.state.plotCfg}
        />
      </div>
    );
  }
}

export default Home

**Comment by chenjianjun571** [comment]
服务端渲染的时候
